#!/usr/bin/racket
#lang racket
(require racket/system)
(require racket/port)

; Returns True:
;(string? (vector-ref (current-command-line-arguments) 0))

(define (owncat filename)
        (system (string-append "echo -n 'Owner: ';" (string-append (string-append "ls -l " filename) "| awk '{print $3}'")))
        (system (string-append "echo -n 'Group: ';" (string-append (string-append "ls -l " filename) "| awk '{print $4}'")))
        (system (string-append "echo -n 'Octal: ';" (string-append (string-append "stat -c '%a %n' " filename) "| awk '{print $1}'")))
        (system (string-append "echo -n 'r/w/x: ';" (string-append (string-append "ls -l " filename) "| awk '{print $1}' | sed 's/#\\.//'"))))

(define (system-display command)
        (display (with-output-to-string (lambda () command))))

(if (= 0 (vector-length (current-command-line-arguments)))
    (exit)
    (system-display (owncat (vector-ref (current-command-line-arguments) 0))))
